language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.11.2
cache: bundler
addons:
  postgresql: "9.4"
env:
  global:
    - GITHUB_TOKEN="6a21f190e3422bf89afa8b360d923b0c30e8fbfa"
    - TEST_DATABASE_URL='postgres://localhost/ossert_test'
    - REDIS_URL='redis://localhost'
    - STACKOVERFLOW_KEY="KM0jqjZaKZZYULSYGXEuhw(("
before_script:
  - bundle exec rake db:test:prepare
script:
 - bundle exec rspec
