---
:agility:
  :last_year:
    issues_processed_in_avg:
    - 1825.84
    - 944.89
    - 462.24
    - 202.59
    - 35.91
    issues_processed_in_median:
    - 1825.92
    - 1004.57
    - 505.11
    - 199.64
    - 18.27
    issues_closed_percent:
    - 96.76
    - 72.77
    - 48.8
    - 25.44
    - 0.68
    issues_actual_count:
    - 1021.22
    - 271.98
    - 98.37
    - 36.28
    - 3.08
    issues_all_count:
    - 1832.0
    - 467.38
    - 198.47
    - 66.29
    - 5.39
    pr_processed_in_avg:
    - 1825.05
    - 991.17
    - 494.56
    - 191.5
    - 20.41
    pr_processed_in_median:
    - 1825.28
    - 1109.68
    - 579.23
    - 236.24
    - 10.62
    pr_closed_percent:
    - 98.63
    - 81.55
    - 57.51
    - 29.3
    - 0.41
    pr_actual_count:
    - 972.0
    - 133.04
    - 44.29
    - 12.88
    - 1.05
    pr_all_count:
    - 3302.5
    - 947.44
    - 270.77
    - 66.62
    - 5.2
    releases_count:
    - 102.7
    - 43.88
    - 17.6
    - 5.47
    - 0.51
    commits:
    - 5965.67
    - 1666.52
    - 729.61
    - 163.0
    - 10.79
  :quarter:
    issues_processed_in_avg:
    - 1826.02
    - 1092.42
    - 576.7
    - 240.51
    - 29.25
    issues_processed_in_median:
    - 1825.96
    - 1106.35
    - 602.35
    - 250.48
    - 19.53
    issues_closed_percent:
    - 95.58
    - 58.01
    - 32.85
    - 14.63
    - 0.23
    issues_actual_count:
    - 583.77
    - 177.55
    - 86.34
    - 31.31
    - 1.92
    issues_all_count:
    - 949.33
    - 298.35
    - 110.4
    - 38.41
    - 2.63
    pr_processed_in_avg:
    - 1825.93
    - 1055.06
    - 447.09
    - 185.99
    - 15.94
    pr_processed_in_median:
    - 1825.82
    - 1036.53
    - 425.83
    - 156.84
    - 8.54
    pr_closed_percent:
    - 98.45
    - 73.16
    - 49.99
    - 27.58
    - 0.26
    pr_actual_count:
    - 622.0
    - 53.17
    - 20.19
    - 5.59
    - 0.26
    pr_all_count:
    - 1056.0
    - 258.0
    - 87.72
    - 23.76
    - 1.67
    releases_count:
    - 31.42
    - 6.31
    - 1.53
    - 0.0
    - 0.0
    commits:
    - 1517.0
    - 419.19
    - 147.52
    - 40.6
    - 2.26
  :total:
    issues_closed_percent:
    - 97.71
    - 83.57
    - 66.89
    - 42.63
    - 0.61
    issues_non_owner_percent:
    - 99.75
    - 88.95
    - 71.11
    - 44.76
    - 0.46
    issues_with_contrib_comments_percent:
    - 95.86
    - 78.27
    - 57.65
    - 34.28
    - 0.48
    issues_all_count:
    - 6032.75
    - 3026.69
    - 1031.71
    - 330.3
    - 21.7
    issues_processed_in_avg:
    - 898.36
    - 441.33
    - 215.77
    - 91.44
    - 12.18
    issues_processed_in_median:
    - 986.96
    - 473.33
    - 220.66
    - 77.23
    - 6.67
    pr_closed_percent:
    - 98.93
    - 88.12
    - 73.38
    - 48.94
    - 0.25
    pr_non_owner_percent:
    - 99.85
    - 88.39
    - 71.76
    - 46.25
    - 0.38
    pr_with_contrib_comments_percent:
    - 134.92
    - 97.29
    - 72.18
    - 43.24
    - 2.01
    pr_all_count:
    - 17813.0
    - 3891.08
    - 982.76
    - 253.25
    - 20.19
    pr_processed_in_avg:
    - 532.01
    - 278.1
    - 149.76
    - 69.02
    - 8.64
    pr_processed_in_median:
    - 552.94
    - 256.61
    - 120.99
    - 48.67
    - 6.72
    first_pr_date_int:
    - 1444188539.04
    - 1391661812.59
    - 1345194554.27
    - 1297349306.0
    - 0.0
    last_pr_date_int:
    - 1475882936.38
    - 1447282420.72
    - 1404106888.41
    - 1343345287.3
    - 0.0
    first_issue_date_int:
    - 1438615105.38
    - 1379165796.16
    - 1324777904.93
    - 1266185526.58
    - 0.0
    last_issue_date_int:
    - 1475628413.69
    - 1443988198.22
    - 1399030149.95
    - 1329247271.25
    - 0.0
    last_release_date_int:
    - 1470671575.37
    - 1428187974.55
    - 1376774480.13
    - 1304032448.41
    - 0.0
    releases_count:
    - 349.06
    - 170.9
    - 82.19
    - 33.13
    - 8.84
    commits_count_since_last_release_count:
    - 5673.0
    - 483.73
    - 173.45
    - 41.78
    - 5.68
    stale_branches_count:
    - 172.5
    - 74.95
    - 24.17
    - 6.61
    - 1.23
    life_period:
    - 210085390.52
    - 154259876.42
    - 104864451.11
    - 56096571.43
    - 6563880.9
    last_changed:
    - 1476676354.98
    - 1446483393.83
    - 1400687368.76
    - 1335087039.86
    - 0.0
:community:
  :total:
    dependants_count:
    - 45929.0
    - 7126.38
    - 3112.8
    - 741.36
    - 17.35
    users_creating_issues_count:
    - 3539.33
    - 1337.17
    - 406.97
    - 134.0
    - 11.37
    contributors_count:
    - 772.65
    - 324.77
    - 143.05
    - 51.91
    - 7.97
    users_commenting_issues_count:
    - 4531.75
    - 1716.43
    - 684.24
    - 253.11
    - 16.37
    users_creating_pr_count:
    - 4035.0
    - 836.17
    - 261.51
    - 89.96
    - 9.8
    users_commenting_pr_count:
    - 1821.0
    - 694.52
    - 253.61
    - 96.25
    - 8.97
    watchers_count:
    - 3134.0
    - 673.56
    - 209.02
    - 70.95
    - 8.88
    stargazers_count:
    - 24816.17
    - 7613.1
    - 3485.97
    - 1205.73
    - 99.25
    forks_count:
    - 11617.0
    - 3283.4
    - 1374.4
    - 376.63
    - 28.72
    users_involved_count:
    - 45828.67
    - 12964.77
    - 5148.76
    - 1739.39
    - 154.62
    users_involved_no_stars_count:
    - 12471.75
    - 4132.05
    - 1424.8
    - 449.37
    - 44.4
    total_downloads_count:
    - 97483738.82
    - 46470793.36
    - 19612159.58
    - 6587265.74
    - 366462.57
    questions_count:
    - 55079.0
    - 8286.92
    - 3116.04
    - 1039.37
    - 12.13
    questions_resolved_percent:
    - 99.52
    - 68.35
    - 51.67
    - 32.32
    - 0.06
  :quarter:
    users_creating_issues_count:
    - 288.75
    - 65.07
    - 26.79
    - 8.71
    - 0.52
    users_commenting_issues_count:
    - 640.6
    - 168.5
    - 49.11
    - 14.66
    - 0.9
    users_creating_pr_count:
    - 180.67
    - 37.71
    - 10.69
    - 3.15
    - 0.21
    users_commenting_pr_count:
    - 132.2
    - 34.58
    - 10.41
    - 3.29
    - 0.11
    stargazers_count:
    - 1764.25
    - 428.24
    - 143.62
    - 53.92
    - 3.81
    forks_count:
    - 911.33
    - 298.67
    - 85.74
    - 20.39
    - 1.46
    users_involved_count:
    - 2676.75
    - 1237.4
    - 330.79
    - 109.11
    - 7.95
    users_involved_no_stars_count:
    - 977.56
    - 256.89
    - 100.17
    - 30.91
    - 2.66
    total_downloads_count:
    - 10377442.86
    - 5559039.29
    - 2789865.48
    - 945801.18
    - 45001.56
    questioner_rep_median:
    - 66389.0
    - 33215.0
    - 13632.57
    - 3427.65
    - 37.7
    question_view_sum:
    - 51078.67
    - 24019.0
    - 12240.92
    - 4105.81
    - 42.35
    answers_avg:
    - 3.2
    - 1.86
    - 1.04
    - 0.57
    - 0.0
    question_score_sum:
    - 242.5
    - 150.5
    - 64.0
    - 23.02
    - 0.24
    questioners_count:
    - 371.0
    - 224.13
    - 117.78
    - 41.36
    - 0.57
    questions_count:
    - 424.0
    - 251.0
    - 135.33
    - 50.2
    - 0.64
    questions_resolved_percent:
    - 99.63
    - 65.93
    - 49.18
    - 31.75
    - 0.01
  :last_year:
    users_creating_issues_count:
    - 1042.88
    - 372.86
    - 138.63
    - 39.03
    - 2.65
    users_commenting_issues_count:
    - 1984.6
    - 547.89
    - 167.15
    - 50.31
    - 3.37
    users_creating_pr_count:
    - 652.0
    - 146.46
    - 59.62
    - 18.05
    - 1.9
    users_commenting_pr_count:
    - 241.53
    - 76.54
    - 26.76
    - 8.61
    - 1.01
    stargazers_count:
    - 7868.75
    - 2471.11
    - 892.33
    - 303.79
    - 20.18
    forks_count:
    - 3702.0
    - 1055.5
    - 345.7
    - 85.2
    - 6.34
    users_involved_count:
    - 12766.0
    - 5076.33
    - 1687.15
    - 520.88
    - 35.0
    users_involved_no_stars_count:
    - 3108.88
    - 967.67
    - 341.05
    - 111.44
    - 9.65
    total_downloads_count:
    - 34600340.53
    - 16810599.28
    - 7173232.18
    - 2672412.73
    - 141733.3
    questioner_rep_median:
    - 66389.0
    - 42744.6
    - 14500.57
    - 3613.07
    - 76.9
    question_view_sum:
    - 857155.0
    - 379079.5
    - 160089.82
    - 60638.62
    - 542.97
    answers_avg:
    - 5.0
    - 2.02
    - 1.08
    - 0.62
    - 0.0
    question_score_sum:
    - 2793.0
    - 1098.33
    - 425.11
    - 130.33
    - 1.51
    questioners_count:
    - 3127.0
    - 1195.86
    - 613.47
    - 203.28
    - 2.52
    questions_count:
    - 4900.0
    - 1757.0
    - 1013.8
    - 360.45
    - 3.65
    questions_resolved_percent:
    - 99.84
    - 69.87
    - 52.38
    - 34.18
    - 0.07
