stats:
  agility:
    total:
      metrics:
        - issues_closed_percent
        - issues_non_owner_percent
        - issues_with_contrib_comments_percent
        - issues_all_count
        - issues_processed_in_avg
        - issues_processed_in_median
        - pr_closed_percent
        - pr_non_owner_percent
        - pr_with_contrib_comments_percent
        - pr_all_count
        - pr_processed_in_avg
        - pr_processed_in_median
        - first_pr_date_int
        - last_pr_date_int
        - first_issue_date_int
        - last_issue_date_int
        - last_release_date_int
        - releases_count
        - commits_count_since_last_release_count
        - stale_branches_count
        - life_period
        - last_changed
      uniq_attributes:
        - dependencies
        - issues_open
        - issues_closed
        - issues_owner
        - issues_non_owner
        - issues_with_contrib_comments
        - issues_total
        - pr_open
        - pr_merged
        - pr_closed
        - pr_owner
        - pr_non_owner
        - pr_with_contrib_comments
        - pr_total
        - releases_total_gh
        - releases_total_rg
        - stale_branches
        - branches
      attributes:
        dependencies: Array
        issues_open: Array
        issues_closed: Array
        issues_owner: Array
        issues_non_owner: Array
        issues_with_contrib_comments: Array
        issues_total: Array
        issues_processed_in_avg: Ossert::TooLong
        issues_processed_in_median: Ossert::TooLong
        pr_open: Array
        pr_merged: Array
        pr_closed: Array
        pr_owner: Array
        pr_non_owner: Array
        pr_with_contrib_comments: Array
        pr_total: Array
        pr_processed_in_avg: Ossert::TooLong
        pr_processed_in_median: Ossert::TooLong
        releases_total_gh: Array
        releases_total_rg: Array
        stale_branches: Array
        branches: Array
        first_pr_date: Ossert::Zero
        last_pr_date: Ossert::Zero
        first_issue_date: Ossert::Zero
        last_issue_date: Ossert::Zero
        last_release_date: Ossert::Zero
        commits_count_since_last_release: Ossert::Zero
        last_year_commits: Ossert::Zero
    quarter:
      metrics:
        - issues_processed_in_avg
        - issues_processed_in_median
        - issues_closed_percent
        - issues_actual_count
        - issues_all_count
        - pr_processed_in_avg
        - pr_processed_in_median
        - pr_closed_percent
        - pr_actual_count
        - pr_all_count
        - releases_count
        - commits
      uniq_attributes:
        - issues_open
        - issues_closed
        - issues_total
        - issues_actual
        - pr_open
        - pr_closed
        - pr_total
        - pr_actual
        - branches
        - releases
        - releases_total_gh
        - releases_total_rg
      attributes:
        issues_open: Array
        issues_closed: Array
        issues_total: Array
        issues_actual: Array
        pr_open: Array
        pr_merged: Array
        pr_closed: Array
        pr_total: Array
        pr_actual: Array
        branches: Array
        releases: Array
        releases_total_gh: Array
        releases_total_rg: Array
        commits: Ossert::Zero
        issues_processed_in_days: Array
        pr_processed_in_days: Array
  community:
    total:
      metrics:
        - dependants_count
        - users_creating_issues_count
        - contributors_count
        - users_commenting_issues_count
        - users_creating_pr_count
        - users_commenting_pr_count
        - watchers_count
        - stargazers_count
        - forks_count
        - users_involved_count
        - users_involved_no_stars_count
        - total_downloads_count
        - questions_count
        - questions_resolved_percent
        - last_question_date_int
      uniq_attributes:
        - dependants
        - users_creating_issues
        - users_commenting_issues
        - users_creating_pr
        - users_commenting_pr
        - contributors
        - watchers
        - stargazers
        - forks
        - users_involved
        - owners_github
        - owners_rubygems
      attributes:
        dependants: Array
        users_creating_issues: Array
        users_commenting_issues: Array
        users_creating_pr: Array
        users_commenting_pr: Array
        contributors: Array
        watchers: Array
        stargazers: Array
        forks: Array
        users_involved: Array
        owners_github: Array
        owners_rubygems: Array
        total_downloads: Ossert::Zero
        delta_downloads: Ossert::Zero
        questions_count: Ossert::Zero
        questions_resolved_count: Ossert::Zero
        last_question_date: Ossert::Zero
    quarter:
      metrics:
        - users_creating_issues_count
        - users_commenting_issues_count
        - users_creating_pr_count
        - users_commenting_pr_count
        - stargazers_count
        - forks_count
        - users_involved_count
        - users_involved_no_stars_count
        - total_downloads_count
        - questioner_rep_median
        - question_view_sum
        - answers_avg
        - question_score_sum
        - questioners_count
        - questions_count
        - questions_resolved_percent
      uniq_attributes:
        - users_creating_issues
        - users_commenting_issues
        - users_creating_pr
        - users_commenting_pr
        - contributors
        - stargazers
        - forks
        - users_involved
        - owners_github
        - owners_rubygems
        - questioners
        - questions
        - questions_resolved
      absolute_attributes:
        - total_downloads
      attributes:
        users_creating_issues: Array
        users_commenting_issues: Array
        users_creating_pr: Array
        users_commenting_pr: Array
        contributors: Array
        stargazers: Array
        forks: Array
        users_involved: Array
        download_divergence: Ossert::Zero
        total_downloads: Ossert::Zero
        delta_downloads: Ossert::Zero
        questions: Array
        questions_resolved: Array
        questioners: Array
        questioner_rep: Array
        question_view: Array
        question_score: Array
        answers: Array
